services:
  - type: web
    name: cau-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        sync: false

  - type: web
    name: cau-frontend
    env: node
    rootDir: client
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s build"
